# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "We Heart It Screensaver" do

pod 'NXOAuth2Client', '~> 1.2.2', :inhibit_warnings => true
pod 'AFNetworking', '~> 2.0'

end

