# Uncomment this line to define a global platform for your project
platform :osx, "10.8"

target "We Heart It Screensaver" do

pod 'NXOAuth2Client', '~> 1.2.2', :inhibit_warnings => true
pod 'AFNetworking', '~> 1.3.3'

end

